INDIRECTION_COLUMN = 0
TIMESTAMP_COLUMN = 1
SCHEMA_ENCODING_COLUMN = 2
BASE_ID_COLUMN = 3

PAGE_MAX_ROWS = 512
PAGE_RANGE = 16
METACOLUMN_NUM = 4
NULL_VAL = (1 << 63) - 1
BUFFERPOOL_SIZE = 50
MERGE_STACK_SIZE = 1